name: ubntai
base: core24
version: '0.0.1'
summary: Ubuntu AI Assistant
description: |
  A smart assistant for Ubuntu users.

grade: stable
confinement: strict

parts:
  ubntai:
    plugin: cmake
    source: .

    build-packages:
      - qt6-base-dev
      - qt6-base-dev-tools       # uic, moc needed for .ui files
      - qt6-tools-dev
      - qt6-multimedia-dev
      - cmake
      - g++
      - libopengl-dev            # fixes WrapOpenGL not found
      - libgl-dev                # OpenGL headers

    stage-packages:
      - libgl1
      - libopengl0
      - libqt6core6
      - libqt6gui6
      - libqt6network6
      - libqt6sql6
      - libqt6widgets6
      - qt6-image-formats-plugins  # if you're using image resources
      - libproxy1-plugin-gsettings
      - libproxy1v5

    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp ./ubntai $SNAPCRAFT_PART_INSTALL/bin/ubntai
      echo "✅ Binary copied to bin/ubntai"

apps:
  ubntai:
    command: bin/ubntai
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network
