name: ubntai
base: core24
version: '0.0.1'
summary: Ubuntu AI Assistant
description: |
  A smart assistant for Ubuntu users.

grade: stable
confinement: strict

parts:
  ubntai:
    plugin: cmake
    source: .

    build-packages:
      - qt6-base-dev
      - qt6-base-dev-tools
      - qt6-tools-dev
      - qt6-multimedia-dev
      - cmake
      - g++
      - libopengl-dev
      - libgl-dev
      - libxcb-cursor0
      - libxcb-keysyms1-dev
      - libxkbcommon-dev

    stage-packages:
      - libgl1
      - libopengl0
      - libqt6core6
      - libqt6gui6
      - libqt6network6
      - libqt6sql6
      - libqt6widgets6
      - qt6-image-formats-plugins
      - libproxy1-plugin-gsettings
      - libproxy1v5
      - libxcb-cursor0
      - libxcb-keysyms1
      - libxkbcommon0
      - libsqlite3-0

      # Qt6 plugin and theme packages
      - qt6-gtk-platformtheme
      - qt6-qpa-plugins   # includes xcb

    override-build: |
      craftctl default
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp ./ubntai $SNAPCRAFT_PART_INSTALL/bin/ubntai
      echo "✅ Binary copied to bin/ubntai"

      # Ensure plugins like Fusion are manually included if necessary
      FUSION_PLUGIN=$(find /usr/lib -name libqtfusionstyle.so | head -n 1 || true)
      if [ -f "$FUSION_PLUGIN" ]; then
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins/styles
        cp "$FUSION_PLUGIN" $SNAPCRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins/styles/
        echo "✅ Fusion style plugin manually included from $FUSION_PLUGIN"
      else
        echo "⚠️ Fusion style plugin not found"
      fi

      # Ensure QSQLITE plugin is copied
      SQLITE_PLUGIN=$(find /usr/lib -name libqsqlite.so | head -n 1 || true)
      if [ -f "$SQLITE_PLUGIN" ]; then
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins/sqldrivers
        cp "$SQLITE_PLUGIN" $SNAPCRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins/sqldrivers/
        echo "✅ QSQLITE plugin copied from $SQLITE_PLUGIN"
      else
        echo "❌ Could not find libqsqlite.so — SQLite plugin may not load"
      fi

apps:
  ubntai:
    command: bin/ubntai
    environment:
      QT_QPA_PLATFORM_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins/platforms
      QT_PLUGIN_PATH: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/qt6/plugins
      QT_QPA_PLATFORMTHEME: gtk3  # or qt6gtk2 if applicable
      QT_QPA_PLATFORM: xcb
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/libproxy
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network
