name: ubntai
version: 0.0.1
summary: No more hectic hours to troubleshoot errors, just ask and simply troubleshoot
description: |
  Ubntai is an AI-based Ubuntu Assistant that helps you learn Ubuntu, troubleshoot errors,
  install packages, and manage dependencies with ease.

base: core22
confinement: devmode
grade: devel

apps:
  ubntai:
    command: usr/local/bin/ubntai
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - network

parts:
  ubntai:
    plugin: cmake
    source: .
    build-packages:
        - qt6-base-dev
        - qt6-multimedia-dev
        - qt6-tools-dev
        - cmake
        - g++
    stage-packages:
        - libqt6core6
        - libqt6gui6
        - libqt6widgets6
        - libqt6network6
    cmake-parameters:
        - -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/Qt6

